config/routes.rb
Rails.application.routes.draw do
  scope :api do
    resources :payments
    resources :invoices
  end

  devise_for :users

  # Comment out to use React
  root to: 'pages#index'
  %w[about].each do |page|
    get page, to: 'pages#show'
  end

  # Uncomment to use React
  # root to: 'react_app#index'
  # get '*path', to: 'react_app#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  attribute :amount_currency, default: 'MXN'
end

app/models/payment.rb
class Payment < ApplicationRecord
  attribute :amount_currency, default: 'MXN'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invoices
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = current_user.invoices.where(index_filters)
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = current_user.invoices.build
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = current_user.invoices.build(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = current_user.invoices.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit \
        :emitter_rfc, :receiver_rfc, :fiscal_id,
        :amount_cents, :amount_currency, :emitted_at, :expired_at
    end

    def index_filters
      InvoicesFiltersParser.extract(params)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
    render view
  end

  private

  def view
    request.path.gsub('/', '')
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = current_user.payments.where(PaymentsFiltersParser.extract(params))
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = current_user.payments.build
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = current_user.payments.build(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = current_user.payments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:receiver_clabe, :sender_clabe, :invoice_fiscal_id, :amount_cents, :amount_currency)
    end
end

app/controllers/react_app_controller.rb
class ReactAppController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_json
    current_user.to_json(only: %i[email id])
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/invoices/_form.html.haml
= form_for @invoice do |f|
  - if @invoice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved:"
      %ul
        - @invoice.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :emitter_rfc
    = f.text_field :emitter_rfc
  .field
    = f.label :receiver_rfc
    = f.text_field :receiver_rfc
  .field
    = f.label :fiscal_id
    = f.text_field :fiscal_id
  .field
    = f.label :amount_cents
    = f.number_field :amount_cents
  .field
    = f.label :amount_currency
    = f.text_field :amount_currency
  .field
    = f.label :emitted_at
    = f.datetime_select :emitted_at
  .field
    = f.label :expired_at
    = f.datetime_select :expired_at
  .actions
    = f.submit 'Save'

app/views/invoices/edit.html.haml
%h1 Editing invoice

= render 'form'

= link_to 'Show', @invoice
\|
= link_to 'Back', invoices_path

app/views/invoices/index.html.haml
%h1 Listing invoices

%table
  %thead
    %tr
      %th Emitter rfc
      %th Receiver rfc
      %th Fiscal
      %th Amount cents
      %th Amount currency
      %th Emitted at
      %th Expired at
      %th
      %th
      %th

  %tbody
    - @invoices.each do |invoice|
      %tr
        %td= invoice.emitter_rfc
        %td= invoice.receiver_rfc
        %td= invoice.fiscal_id
        %td= invoice.amount_cents
        %td= invoice.amount_currency
        %td= invoice.emitted_at
        %td= invoice.expired_at
        %td= link_to 'Show', invoice
        %td= link_to 'Edit', edit_invoice_path(invoice)
        %td= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.haml
%h1 New invoice

= render 'form'

= link_to 'Back', invoices_path

app/views/invoices/show.html.haml
%p#notice= notice

%p
  %b Emitter rfc:
  = @invoice.emitter_rfc
%p
  %b Receiver rfc:
  = @invoice.receiver_rfc
%p
  %b Fiscal:
  = @invoice.fiscal_id
%p
  %b Amount cents:
  = @invoice.amount_cents
%p
  %b Amount currency:
  = @invoice.amount_currency
%p
  %b Emitted at:
  = @invoice.emitted_at
%p
  %b Expired at:
  = @invoice.expired_at

= link_to 'Edit', edit_invoice_path(@invoice)
\|
= link_to 'Back', invoices_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HigoRailsStarter
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to 'Home', '/'
      %li= link_to 'About', '/about'

      - if user_signed_in?
        %li= link_to 'Sign out', destroy_user_session_path
      - else
        %li= link_to 'Sign in', new_user_session_path

    = yield

app/views/layouts/react_app.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HigoRailsStarter
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag

    = javascript_pack_tag 'react_app'
    = stylesheet_pack_tag 'react_app', media: 'all'
  %body
    #data{ data: { 'current-user': user_signed_in? ? current_user_json : 'null' } }
    = yield

app/views/pages/about.html.haml
%h1 About

app/views/pages/index.html.haml
%h1 Home

app/views/payments/_form.html.haml
= form_for @payment do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @payment.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :receiver_clabe
    = f.text_field :receiver_clabe
  .field
    = f.label :sender_clabe
    = f.text_field :sender_clabe

  .field
    = f.label :invoice_fiscal_id
    = f.text_field :invoice_fiscal_id

  .field
    = f.label :amount_cents
    = f.number_field :amount_cents
  .field
    = f.label :amount_currency
    = f.text_field :amount_currency

  .field
    = f.label :sent_at
    = f.datetime_select :sent_at

  .actions
    = f.submit 'Save'

app/views/payments/edit.html.haml
%h1 Editing payment

= render 'form'

= link_to 'Show', @payment
\|
= link_to 'Back', payments_path

app/views/payments/index.html.haml
%h1 Listing payments

%table
  %thead
    %tr
      %th Receiver account number
      %th Sender account number
      %th Invoice fiscal
      %th Amount cents
      %th Amount currency
      %th Sent at
      %th
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.receiver_clabe
        %td= payment.sender_clabe
        %td= payment.invoice_fiscal_id
        %td= payment.amount_cents
        %td= payment.amount_currency
        %td= payment.sent_at
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Payment', new_payment_path

app/views/payments/new.html.haml
%h1 New payment

= render 'form'

= link_to 'Back', payments_path

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b Receiver account number:
  = @payment.receiver_clabe
%p
  %b Sender account number:
  = @payment.sender_clabe
%p
  %b Invoice fiscal:
  = @payment.invoice_fiscal_id
%p
  %b Amount cents:
  = @payment.amount_cents
%p
  %b Amount currency:
  = @payment.amount_currency

= link_to 'Edit', edit_payment_path(@payment)
\|
= link_to 'Back', payments_path

app/views/react_app/index.html.haml
#react-app